INSERT INTO courses (id, category_id, teacher_id, course_name, course_description, price, quota) VALUES
(1, 1, 72, 'Python for Beginners', 'Learn Python programming from scratch with hands-on projects', 150000, 30),
(2, 1, 72, 'Advanced JavaScript', 'Deep dive into modern JS, ES6+, async programming and frameworks', 350000, 25),
(3, 2, 72, 'Data Analysis with Excel & Python', 'Master data analysis tools and techniques for real-world datasets', 299000, 20),
(4, 2, 72, 'SQL for Data Science', 'Use SQL to query, analyze and visualize data effectively', 199000, 0),
(5, 3, 78, 'Ethical Hacking Fundamentals', 'Introduction to penetration testing and cybersecurity concepts', 450000, 15),
(6, 3, 78, 'Network Security Essentials', 'Protect networks from threats with modern security practices', 400000, 40),
(7, 4, 74, 'AWS Cloud Practitioner Prep', 'Prepare for the AWS Cloud Practitioner certification exam', 500000, 50),
(8, 4, 74, 'Google Cloud for Beginners', 'Get started with Google Cloud Platform services and tools', 350000, 35),
(9, 5, 72, 'Machine Learning with Python', 'Build and train ML models using scikit-learn and TensorFlow', 499000, 20),
(10, 5, 72, 'Introduction to AI', 'Explore the fundamentals of artificial intelligence and its applications', 0, 100),
(11, 6, 72, 'UI/UX Design Principles', 'Learn user-centered design thinking and prototyping with Figma', 250000, 30),
(12, 6, 78, 'Web Design for Beginners', 'Build beautiful websites with HTML, CSS and basic design principles', 0, 60),
(13, 7, 74, 'MySQL Database Administration', 'Install, configure and manage MySQL databases in production', 300000, 0),
(14, 8, 87, 'Cisco Networking Basics', 'Understand networking concepts, protocols and Cisco device configuration', 425000, 45),
(15, 9, 87, 'Flutter Mobile Development', 'Build cross-platform iOS and Android apps with Flutter and Dart', 375000, 25),
(16, 10, 87, 'CI/CD with Jenkins & Docker', 'Automate build, test and deployment pipelines using DevOps tools', 450000, 20),
(17, 11, 78, 'Business Communication Skills', 'Improve professional writing, presentation and leadership communication', 175000, 50),
(18, 12, 78, 'Social Media Marketing', 'Create and manage effective marketing campaigns across social platforms', 225000, 40);